version: 2.1
orbs:
  python: circleci/python@2.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install pytest  # Install pytest to run tests
      - run:
          name: Run Unit Tests
          command: |
            python -m unittest TestTriangle.py  # Run the TestTriangle tests
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
